const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openDirectoryDialog: () => ipcRenderer.invoke('dialog:openDirectory'),
  getProjects: () => ipcRenderer.invoke('config:getProjects'),
  saveProjects: (config) => ipcRenderer.invoke('config:saveProjects', config),
  getRecentSessions: (projectPath) => ipcRenderer.invoke('sessions:getRecent', projectPath),
  saveSessions: (projectPath, sessionIds) => ipcRenderer.invoke('sessions:save', projectPath, sessionIds),
  loadSessions: (projectPath) => ipcRenderer.invoke('sessions:load', projectPath),
  getSessionTitle: (projectPath, sessionId) => ipcRenderer.invoke('sessions:getTitle', projectPath, sessionId),
  readClaudeMd: (projectPath) => ipcRenderer.invoke('claudemd:read', projectPath),
  saveClaudeMd: (projectPath, content) => ipcRenderer.invoke('claudemd:save', projectPath, content),
  readDir: (dirPath) => ipcRenderer.invoke('fs:readDir', dirPath),
  gitStatus: (projectPath) => ipcRenderer.invoke('git:status', projectPath),
  gitBranch: (projectPath) => ipcRenderer.invoke('git:branch', projectPath),
  gitStageFile: (projectPath, filePath) => ipcRenderer.invoke('git:stageFile', projectPath, filePath),
  gitUnstageFile: (projectPath, filePath) => ipcRenderer.invoke('git:unstageFile', projectPath, filePath),
  gitStageAll: (projectPath) => ipcRenderer.invoke('git:stageAll', projectPath),
  gitUnstageAll: (projectPath) => ipcRenderer.invoke('git:unstageAll', projectPath),
  gitCommit: (projectPath, message) => ipcRenderer.invoke('git:commit', projectPath, message),
  gitPull: (projectPath) => ipcRenderer.invoke('git:pull', projectPath),
  gitPush: (projectPath) => ipcRenderer.invoke('git:push', projectPath),
  gitDiscardFile: (projectPath, filePath) => ipcRenderer.invoke('git:discardFile', projectPath, filePath),
  getLaunchConfigs: (projectPath) => ipcRenderer.invoke('launch:getConfigs', projectPath),
  getUsage: () => ipcRenderer.invoke('usage:getAll'),
  getVersion: () => ipcRenderer.invoke('app:getVersion'),
  onUpdateAvailable: (callback) => ipcRenderer.on('update:available', (_, info) => callback(info)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update:downloaded', (_, info) => callback(info)),
  installUpdate: () => ipcRenderer.invoke('update:install')
});
